name: "Setup bx"
description: "Installs the latest version of bx (with bundled dependencies and common packages)"
runs:
 using: "composite"
 steps:
   - run: $GITHUB_ACTION_PATH/setup.sh
     shell: bash
   - run: echo "::add-path::packages/bin"
     shell: bash